#include freepbx_custom_fix_missing_contexts.conf

[from-internal-custom]
exten => 1234,1,Answer()
same => n,Playback(demo-congrats)
same => n,Hangup()
exten => 1000,1,Answer()
same => n,Dial(PJSIP/student,10) ; wait 10 seconds at maximum
same => n,Hangup()
