[student]
type=endpoint             ; always of type "endpoint"
aors=student              ; AORs (addresses of record) of the terminal
auth=student              ; authentication data
disallow=all              ; initially, no codec allowed
allow=gsm,ulaw,alaw,g726  ; codecs allowed
context=from-internal     ; dialplan context
dtmf_mode=rfc4733         ; dialing mode
rtp_symmetric=yes         ; force symmetric rtp data (ports)
rewrite_contact=yes       ; update "Contact" header with the IP
