[auth-userpass](!)
type=auth
auth_type=userpass
password=hotel26  ; WARNING: all terminals use the same password (POTENTIAL RISK!!!!!)

;=============== EMERGENCY

[emergency](auth-userpass)
username=emergency


;=============== RECEPTION

[reception](auth-userpass)
username=reception


;=============== ROOMS

[room-101](auth-userpass)
username=room-101
[room-102](auth-userpass)
username=room-102
[room-103](auth-userpass)
username=room-103

[room-201](auth-userpass)
username=room-201
[room-202](auth-userpass)
username=room-202
[room-203](auth-userpass)
username=room-203

[room-301](auth-userpass)
username=room-301
[room-302](auth-userpass)
username=room-302
[room-303](auth-userpass)
username=room-303

[room-401](auth-userpass)
username=room-401
[room-402](auth-userpass)
username=room-402
[room-403](auth-userpass)
username=room-403

[room-501](auth-userpass)
username=room-501
[room-502](auth-userpass)
username=room-502
[room-503](auth-userpass)
username=room-503
