[hotel-terminal](!)
type=endpoint
disallow=all
allow=gsm,ulaw,alaw,g726
context=from-room   ; default context (in a room)
dtmf_mode=rfc4733
rtp_symmetric=yes
rewrite_contact=yes


;=============== EMERGENCY

[emergency](hotel-terminal)
auth=emergency
aors=emergency
context=from-emergency ; a specific context for emergency


;=============== RECEPTION

[reception](hotel-terminal)
auth=reception
aors=reception
context=from-reception  ; a specific context also for the reception


;=============== ROOMS

[room-101](hotel-terminal)
auth=room-101
aors=room-101

[room-102](hotel-terminal)
auth=room-102
aors=room-102

[room-103](hotel-terminal)
auth=room-103
aors=room-103

[room-201](hotel-terminal)
auth=room-201
aors=room-201

[room-202](hotel-terminal)
auth=room-202
aors=room-202

[room-203](hotel-terminal)
auth=room-203
aors=room-203

[room-301](hotel-terminal)
auth=room-301
aors=room-301

[room-302](hotel-terminal)
auth=room-302
aors=room-302

[room-303](hotel-terminal)
auth=room-303
aors=room-303

[room-401](hotel-terminal)
auth=room-401
aors=room-401

[room-402](hotel-terminal)
auth=room-402
aors=room-402

[room-403](hotel-terminal)
auth=room-403
aors=room-403

[room-501](hotel-terminal)
auth=room-501
aors=room-501

[room-502](hotel-terminal)
auth=room-502
aors=room-502

[room-503](hotel-terminal)
auth=room-503
aors=room-503

