[aor-single-reg](!)
type=aor
max_contacts=1
remove_existing=yes

[emergency](aor-single-reg)

[reception](aor-single-reg)

[room-101](aor-single-reg)
[room-102](aor-single-reg)
[room-103](aor-single-reg)
[room-201](aor-single-reg)
[room-202](aor-single-reg)
[room-203](aor-single-reg)
[room-301](aor-single-reg)
[room-302](aor-single-reg)
[room-303](aor-single-reg)
[room-401](aor-single-reg)
[room-402](aor-single-reg)
[room-403](aor-single-reg)
[room-501](aor-single-reg)
[room-502](aor-single-reg)
[room-503](aor-single-reg)
